# -*- coding: utf-8 -*-
"""modeling_obesity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJD7F0nUQXGf1BvTzL1H_Oe0QjN_dLmd

# Sistema Preditivo de Obesidade

Este notebook tem como objetivo desenvolver um modelo de Machine Learning
capaz de prever o nível de obesidade de um paciente, com base em dados de hábitos alimentares e estilo de vida.

O projeto foi desenvolvido como parte do Tech Challenge da FIAP,
com foco em apoio à decisão clínica.

#Importação das bibliotecas
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib

"""#Análise do arquivo"""

df = pd.read_csv("Obesity.csv")
df.head()

"""### Dicionário de Dados (Resumo)

- Gender: gênero do paciente
- Age: idade
- Height: altura (m)
- Weight: peso (kg)
- family_history: histórico familiar de sobrepeso
- FAVC: consumo frequente de alimentos calóricos
- FCVC: frequência de consumo de vegetais
- NCP: número de refeições principais
- CAEC: consumo entre refeições
- SMOKE: hábito de fumar
- CH2O: consumo diário de água
- SCC: monitoramento calórico
- FAF: frequência de atividade física
- TUE: tempo de uso de dispositivos eletrônicos
- CALC: consumo de álcool
- MTRANS: meio de transporte
- Obesity: variável alvo (nível de obesidade)

###EDA (Análise Exploratória)
"""

df.info()
df.describe()

plt.figure(figsize=(8,5))
sns.boxplot(x="Obesity", y="Age", data=df)
plt.xticks(rotation=45)
plt.title("Distribuição de Idade por Nível de Obesidade")
plt.show()

# Distribuição dos Níveis de Obesidade

plt.figure(figsize=(10,5))
ax = sns.countplot(x="Obesity", data=df)

plt.ylabel("Quantity")
plt.title("Distribuição dos Níveis de Obesidade")
plt.xticks(rotation=45)

for p in ax.patches:
    ax.annotate(
        f'{int(p.get_height())}',
        (p.get_x() + p.get_width() / 2., p.get_height()),
        ha='center', va='bottom'
    )

plt.show()

plt.figure(figsize=(8,6))
sns.scatterplot(
    data=df,
    x="Height",
    y="Weight",
    hue="Obesity",
    alpha=0.6
)
plt.title("Relação Altura x Peso por Nível de Obesidade")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x="Obesity", y="Weight", data=df)
plt.xticks(rotation=45)
plt.title("Peso por Nível de Obesidade")
plt.show()

"""###Preparação dos dados"""

X = df_obesity.drop("Obesity", axis=1)
y = df_obesity["Obesity"]

num_cols = ["Age", "Height", "Weight", "FCVC", "NCP", "CH2O", "FAF", "TUE"]
cat_cols = [col for col in X.columns if col not in num_cols]

"""###Pipeline"""

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
])

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", model)
])

"""###Treinamento"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

pipeline.fit(X_train, y_train)

"""###Acurácia do modelo"""

y_pred = pipeline.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""##Baixar em estilo .pkl"""

joblib.dump(pipeline, "model.pkl")

files.download("model.pkl")